///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/game.aks
/// Generation time: jue 29 oct 2020 14:31:43 CET
///

/// Song 'game' metadata macros
#define game_address  0x308
#define game_size     633
#define game_end      0x580

/// Song 'game' array declaration
extern void game[game_size];
