///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/intro.aks
/// Generation time: jue 29 oct 2020 14:31:43 CET
///

/// Song 'intro' metadata macros
#define intro_address  0x150
#define intro_size     440
#define intro_end      0x307

/// Song 'intro' array declaration
extern void intro[intro_size];
