///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music1.aks
/// Generation time: mar 27 oct 2020 11:52:14 CET
///

/// Song 'music1' metadata macros
#define music1_address  0x1000
#define music1_size     849
#define music1_end      0x1350

/// Song 'music1' array declaration
extern void music1[music1_size];
