///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/rym.aks
/// Generation time: jue 29 oct 2020 14:31:42 CET
///

/// Song 'rym' metadata macros
#define rym_address  0x581
#define rym_size     1258
#define rym_end      0xa6a

/// Song 'rym' array declaration
extern void rym[rym_size];
