///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/sfx.aks
/// Generation time: jue 29 oct 2020 14:31:42 CET
///

/// Song 'sfx' metadata macros
#define sfx_address  0xa6b
#define sfx_size     121
#define sfx_end      0xae3

/// Song 'sfx' array declaration
extern void sfx[sfx_size];
